[general]
live_config_reload = true

[window]
opacity = 0.9
decorations = "Transparent"
padding.x = 5
padding.y = 27
blur = true

[font]
size = 14
offset.y = 3
normal.family = "BerkeleyMonoVariable Nerd Font"

